const courses = [
    {
      id: 1,
      image: './images/course-2-1.jpg',
      title: "The Power Of Podcast For Storytelling",
      instructor: "Sunil",
      lessons: 10,
      rating: 4.5,
      reviews: 2,
      category1: { name: "Finance", color: "#4285F4" },
      category2: { name: "Lifestyle", color: "#E91E63" },
      price: "Free",
    },
    {
      id: 2,
      image: './images/course-4-1.jpg',
      title: "Mastering Digital Marketing",
      instructor: "Aisha",
      lessons: 12,
      rating: 4.8,
      reviews: 5,
      category1: { name: "Business", color: "#FF9800" },
      category2: { name: "Marketing", color: "#4CAF50" },
      price: "Free",
    },
    {
      id: 3,
      image: './images/course-5-1.jpg',
      title: "Photography Essentials",
      instructor: "Rahul",
      lessons: 8,
      rating: 4.2,
      reviews: 3,
      category1: { name: "Creative", color: "#673AB7" },
      category2: { name: "Photography", color: "#009688" },
      price: "Free",
    },
    {
      id: 4,
      image: './images/course-6-1.jpg',
      title: "Web Development Fundamentals",
      instructor: "Emily",
      lessons: 15,
      rating: 4.9,
      reviews: 10,
      category1: { name: "Technology", color: "#FF5722" },
      category2: { name: "Coding", color: "#3F51B5" },
      price: "Free",
    },
    {
      id: 5,
      image: './images/course11.jpg',
      title: "UI/UX Design Principles",
      instructor: "Jessica",
      lessons: 9,
      rating: 4.6,
      reviews: 4,
      category1: { name: "Design", color: "#FF4081" },
      category2: { name: "Creativity", color: "#00BCD4" },
      price: "Free",
    },
    {
      id: 6,
      image: './images/course12.jpg',
      title: "Financial Freedom Blueprint",
      instructor: "Mark",
      lessons: 11,
      rating: 4.7,
      reviews: 6,
      category1: { name: "Finance", color: "#FFEB3B" },
      category2: { name: "Wealth", color: "#8BC34A" },
      price: "Free",
    },
  ];
  
  export default courses;
  